name: zapcc-test
on: push

jobs:
  zapcc-basic-test:
    runs-on: ubuntu-18.04
    container: docker://srzzumix/zapcc
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set Python environment variable
      run: echo '::set-env name=LD_LIBRARY_PATH::${RUNNER_TOOL_CACHE}/Python/3.8/x64/lib'
    # - run: |
    #     echo ${RUNNER_TOOL_CACHE}
    #     cd /
    #     find . -name python*
    - run: |
        python -c "import sys; print(sys.version)"
